import 'dart:ui';

import 'package:dompet/theme/styles/card_style.dart';
import 'package:dompet/theme/styles/item_group_style.dart';
import 'package:dompet/theme/styles/tile_group_style.dart';
import 'package:dompet/theme/tailwind.dart';
import 'package:forui/forui.dart';
import 'package:forui_phosphor/forui_phosphor.dart';
import 'package:material_ui/material_ui.dart';

export 'package:forui/forui.dart';
export 'package:forui_phosphor/forui_phosphor.dart';

export 'typography_roles.dart';

part 'colors.dart';
part 'gradients.dart';
part 'icons.dart';
part 'style.dart';
part 'typography.dart';

/// Generated by Forui CLI.
///
/// Regenerate using "dart forui theme create --preset aabbbc".
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified function and pass it to [FTheme].
///
/// You can also generate styles to be used in the generated [FThemeData] using:
/// ```shell
/// dart run forui style create [styles]
/// ```
///
/// See:
/// * https://forui.dev/docs/guides/customizing-themes for customizing themes.
/// * https://forui.dev/docs/guides/customizing-widget-styles for customizing individual widget styles.
FThemeData get lightTheme {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = lightColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    cardStyle: cardStyle(colors: colors, typography: typography, style: style, touch: touch),
    tileGroupStyle: tileGroupStyle(
      colors: colors,
      typography: typography,
      style: style,
      hapticFeedback: const FHapticFeedback(),
    ),
    itemGroupStyle: itemGroupStyle(
      colors: colors,
      typography: typography,
      style: style,
      hapticFeedback: const FHapticFeedback(),
      touch: touch,
    ),
    touch: touch,
  );
}

/// Global dark theme data definition for Dompet CE.
FThemeData get darkTheme {
  // Change this to false to use the desktop variant of this theme.
  const touch = true;

  final colors = darkColors;

  final typography = _typography(colors: colors, touch: touch);

  final icons = _icons();

  final style = _style(colors: colors, typography: typography, touch: touch);

  return FThemeData(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    cardStyle: cardStyle(colors: colors, typography: typography, style: style, touch: touch),
    tileGroupStyle: tileGroupStyle(
      colors: colors,
      typography: typography,
      style: style,
      hapticFeedback: const FHapticFeedback(),
    ),
    itemGroupStyle: itemGroupStyle(
      colors: colors,
      typography: typography,
      style: style,
      hapticFeedback: const FHapticFeedback(),
      touch: touch,
    ),
    touch: touch,
  );
}
