part of 'theme.dart';

/// Generated by Forui CLI, enhanced with tabular figures for all numeric content.
///
/// Typography tokens for the generated theme.
FTypography _typography({required FColors colors, required bool touch}) {
  const headingFamily = 'PlusJakartaSans';
  const bodyFamily = 'Inter';
  return FTypography(
    display: _display(colors: colors, touch: touch, fontFamily: headingFamily),
    body: _body(colors: colors, touch: touch, fontFamily: bodyFamily),
  );
}

TextStyle _typefaceStyle({
  required Color color,
  required String fontFamily,
  required double fontSize,
  required double height,
  List<String>? fontFamilyFallback,
}) {
  return TextStyle(
    color: color,
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: fontSize,
    height: height,
    leadingDistribution: TextLeadingDistribution.even,
    fontFeatures: const [FontFeature.tabularFigures()],
  );
}

/// The typographical tokens used for prominent text such as headings.
FTypeface _display({
  required FColors colors,
  required bool touch,
  String fontFamily = FTypeface.defaultFontFamily,
  List<String>? fontFamilyFallback,
}) {
  assert(
    fontFamily.isNotEmpty,
    'fontFamily ($fontFamily) should not be empty.',
  );
  final color = colors.foreground;
  if (touch) {
    return FTypeface(
      fontFamily: fontFamily,
      fontFamilyFallback: fontFamilyFallback,
      xs3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 10,
        height: 1,
      ),
      xs2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 12,
        height: 1,
      ),
      xs: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 14,
        height: 1.25,
      ),
      sm: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 16,
        height: 1.5,
      ),
      md: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 18,
        height: 1.75,
      ),
      lg: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 20,
        height: 1.75,
      ),
      xl: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 22,
        height: 2,
      ),
      xl2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 30,
        height: 2.25,
      ),
      xl3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 36,
        height: 2.5,
      ),
      xl4: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 48,
        height: 1,
      ),
      xl5: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 60,
        height: 1,
      ),
      xl6: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 72,
        height: 1,
      ),
      xl7: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 96,
        height: 1,
      ),
      xl8: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 108,
        height: 1,
      ),
    );
  } else {
    return FTypeface(
      fontFamily: fontFamily,
      fontFamilyFallback: fontFamilyFallback,
      xs3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 8,
        height: 1,
      ),
      xs2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 10,
        height: 1,
      ),
      xs: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 12,
        height: 1,
      ),
      sm: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 14,
        height: 1.25,
      ),
      md: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 16,
        height: 1.5,
      ),
      lg: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 18,
        height: 1.75,
      ),
      xl: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 20,
        height: 1.75,
      ),
      xl2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 22,
        height: 2,
      ),
      xl3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 30,
        height: 2.25,
      ),
      xl4: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 36,
        height: 2.5,
      ),
      xl5: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 48,
        height: 1,
      ),
      xl6: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 60,
        height: 1,
      ),
      xl7: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 72,
        height: 1,
      ),
      xl8: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 96,
        height: 1,
      ),
    );
  }
}

/// The typographical tokens for content and UI text.
FTypeface _body({
  required FColors colors,
  required bool touch,
  String fontFamily = FTypeface.defaultFontFamily,
  List<String>? fontFamilyFallback,
}) {
  assert(
    fontFamily.isNotEmpty,
    'fontFamily ($fontFamily) should not be empty.',
  );
  final color = colors.foreground;
  if (touch) {
    return FTypeface(
      fontFamily: fontFamily,
      fontFamilyFallback: fontFamilyFallback,
      xs3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 10,
        height: 1,
      ),
      xs2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 12,
        height: 1,
      ),
      xs: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 14,
        height: 1.25,
      ),
      sm: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 16,
        height: 1.5,
      ),
      md: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 18,
        height: 1.75,
      ),
      lg: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 20,
        height: 1.75,
      ),
      xl: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 22,
        height: 2,
      ),
      xl2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 30,
        height: 2.25,
      ),
      xl3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 36,
        height: 2.5,
      ),
      xl4: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 48,
        height: 1,
      ),
      xl5: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 60,
        height: 1,
      ),
      xl6: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 72,
        height: 1,
      ),
      xl7: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 96,
        height: 1,
      ),
      xl8: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 108,
        height: 1,
      ),
    );
  } else {
    return FTypeface(
      fontFamily: fontFamily,
      fontFamilyFallback: fontFamilyFallback,
      xs3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 8,
        height: 1,
      ),
      xs2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 10,
        height: 1,
      ),
      xs: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 12,
        height: 1,
      ),
      sm: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 14,
        height: 1.25,
      ),
      md: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 16,
        height: 1.5,
      ),
      lg: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 18,
        height: 1.75,
      ),
      xl: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 20,
        height: 1.75,
      ),
      xl2: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 22,
        height: 2,
      ),
      xl3: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 30,
        height: 2.25,
      ),
      xl4: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 36,
        height: 2.5,
      ),
      xl5: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 48,
        height: 1,
      ),
      xl6: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 60,
        height: 1,
      ),
      xl7: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 72,
        height: 1,
      ),
      xl8: _typefaceStyle(
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontSize: 96,
        height: 1,
      ),
    );
  }
}
