import 'package:dompet/theme/typography_roles.dart';
import 'package:flutter/widgets.dart';
import 'package:forui/forui.dart';

// Auto-generated Forui ignores
// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FItemGroupStyle itemGroupStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required FHapticFeedback hapticFeedback,
  required bool touch,
}) => FItemGroupStyle(
  decoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: colors.border, width: style.borderWidth),
      borderRadius: style.borderRadius.lg,
    ),
  ),
  dividerColor: .all(colors.border),
  dividerWidth: style.borderWidth,
  slideableItems: const .all(true),
  slidePressHapticFeedback: hapticFeedback.selectionClick,
  itemStyles: _itemStyles(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  ),
  spacing: 4,
);

FItemStyles _itemStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primary = _itemStyle(
    colors: colors,
    typography: typography,
    style: style,
    touch: touch,
  );
  return FItemStyles(
    FVariants.from(
      primary,
      variants: {
        [.primary]: primary,
        [.destructive]: .delta(
          contentStyle: _itemContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.destructive,
            foreground: colors.destructive,
            mutedForeground: colors.destructive,
            touch: touch,
          ),
          rawContentStyle: _rawItemContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.primary,
            color: colors.primary,
            touch: touch,
          ),
        ),
      },
    ),
  );
}

FItemStyle _itemStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) => FItemStyle(
  backgroundColor: FVariants(
    colors.background,
    variants: {
      [.disabled]: colors.background,
    },
  ),
  contentDecoration: .from(
    ShapeDecoration(
      shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
      color: colors.background,
    ),
    variants: {
      [.hovered, .pressed]: .shapeDelta(color: colors.secondary),
      [.disabled]: const .shapeDelta(),
      [.selected]: .shapeDelta(color: colors.secondary),
      [.selected.and(.disabled)]: .shapeDelta(
        color: colors.disable(colors.secondary),
      ),
    },
  ),
  contentStyle: .inherit(
    colors: colors,
    typography: typography,
    prefix: colors.primary,
    foreground: colors.foreground,
    mutedForeground: colors.mutedForeground,
    touch: touch,
  ),
  rawContentStyle: .inherit(
    colors: colors,
    typography: typography,
    prefix: colors.foreground,
    color: colors.foreground,
    touch: touch,
  ),
  tappableStyle: style.tappableStyle.copyWith(
    motion: FTappableMotion.none,
    pressedEnterDuration: .zero,
    pressedExitDuration: const Duration(milliseconds: 25),
  ),
  focusedOutlineStyle: style.focusedOutlineStyle.copyWith(
    spacing: -style.borderWidth,
  ),
  padding: const .symmetric(horizontal: 4),
);

FItemContentStyle _itemContentStyle({
  required FColors colors,
  required FTypography typography,
  required Color prefix,
  required Color foreground,
  required Color mutedForeground,
  required bool touch,
}) {
  final disabledMutedForeground = colors.disable(mutedForeground);
  return FItemContentStyle(
    prefixIconStyle: .from(
      IconThemeData(color: prefix, size: typography.body.md.fontSize),
      variants: {
        [.disabled]: .delta(color: colors.disable(prefix)),
      },
    ),
    titleTextStyle: .from(
      typography.bodyPrimary.copyWith(color: foreground),
      variants: {
        [.disabled]: .delta(color: colors.disable(foreground)),
      },
    ),
    subtitleTextStyle: .from(
      typography.bodySecondary.copyWith(color: mutedForeground),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    detailsTextStyle: .from(
      typography.bodySecondary.copyWith(color: mutedForeground),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    suffixIconStyle: .from(
      IconThemeData(color: mutedForeground, size: typography.body.md.fontSize),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    suffixedPadding: touch ? const .fromSTEB(10, 12.5, 6, 12.5) : const .fromSTEB(10, 6.5, 5, 6.5),
    unsuffixedPadding: touch
        ? const .symmetric(horizontal: 10, vertical: 12.5)
        : const .symmetric(horizontal: 10, vertical: 6.5),
    prefixIconSpacing: 8,
    titleSpacing: 4,
    middleSpacing: 4,
    suffixIconSpacing: 8,
  );
}

FRawItemContentStyle _rawItemContentStyle({
  required FColors colors,
  required FTypography typography,
  required Color prefix,
  required Color color,
  required bool touch,
}) => FRawItemContentStyle(
  prefixIconStyle: .from(
    IconThemeData(color: prefix, size: typography.body.md.fontSize),
    variants: {
      [.disabled]: .delta(color: colors.disable(prefix)),
    },
  ),
  childTextStyle: FVariants(
    typography.bodyPrimary.copyWith(color: color),
    variants: {
      [.disabled]: typography.bodyPrimary.copyWith(color: colors.disable(color)),
    },
  ),
  padding: touch ? const .symmetric(horizontal: 10, vertical: 12.5) : const .symmetric(horizontal: 10, vertical: 6.5),
  prefixIconSpacing: 8,
);
