import 'package:dompet/theme/typography_roles.dart';
import 'package:flutter/widgets.dart';
import 'package:forui/forui.dart';

// Auto-generated Forui ignores
// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FTileGroupStyle tileGroupStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required FHapticFeedback hapticFeedback,
}) => .new(
  decoration: ShapeDecoration(
    shape: RoundedSuperellipseBorder(
      side: BorderSide(color: colors.border, width: style.borderWidth),
      borderRadius: style.borderRadius.lg,
    ),
  ),
  dividerColor: .all(colors.border),
  dividerWidth: style.borderWidth,
  slideableTiles: const .all(true),
  slidePressHapticFeedback: hapticFeedback.selectionClick,
  labelTextStyle: FVariants.from(
    typography.bodyPrimary.copyWith(
      color: style.formFieldStyle.labelTextStyle.base.color ?? colors.foreground,
      fontWeight: .w600,
    ),
    variants: {
      [.disabled]: .delta(color: colors.disable(colors.foreground)),
    },
  ),
  tileStyles: FTileStyles(
    FVariants.from(
      _tileStyle(colors: colors, typography: typography, style: style).copyWith(
        contentDecoration: .delta([
          .all(const .shapeDelta(shape: RoundedSuperellipseBorder())),
        ]),
      ),
      variants: {
        [.primary]: const .delta(),
        [.destructive]: .delta(
          contentStyle: _tileContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.destructive,
            foreground: colors.destructive,
            mutedForeground: colors.destructive,
          ),
          rawContentStyle: _rawTileContentStyle(
            colors: colors,
            typography: typography,
            prefix: colors.destructive,
            color: colors.destructive,
          ),
        ),
      },
    ),
  ),
  descriptionTextStyle: style.formFieldStyle.descriptionTextStyle.apply([
    .all(
      .delta(
        fontSize: typography.caption.fontSize,
        height: typography.caption.height,
      ),
    ),
  ]),
  errorTextStyle: style.formFieldStyle.errorTextStyle.apply([
    .all(
      .delta(
        fontSize: typography.caption.fontSize,
        height: typography.caption.height,
      ),
    ),
  ]),
);

FTileStyle _tileStyle({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
}) => FTileStyle(
  backgroundColor: .all(colors.card),
  contentDecoration: FVariants.from(
    ShapeDecoration(
      shape: RoundedSuperellipseBorder(
        side: BorderSide(color: colors.border, width: style.borderWidth),
        borderRadius: style.borderRadius.md,
      ),
      color: colors.card,
    ),
    variants: {
      [.hovered, .pressed]: .shapeDelta(color: colors.secondary),
      [.disabled]: .shapeDelta(color: colors.disable(colors.secondary)),
    },
  ),
  contentStyle: _tileContentStyle(
    colors: colors,
    typography: typography,
    prefix: colors.primary,
    foreground: colors.foreground,
    mutedForeground: colors.mutedForeground,
  ),
  rawContentStyle: _rawTileContentStyle(
    colors: colors,
    typography: typography,
    prefix: colors.primary,
    color: colors.foreground,
  ),
  tappableStyle: style.tappableStyle.copyWith(
    motion: FTappableMotion.none,
    pressedEnterDuration: .zero,
    pressedExitDuration: const Duration(milliseconds: 25),
  ),
  focusedOutlineStyle: style.focusedOutlineStyle.copyWith(
    spacing: -style.borderWidth * 2,
  ),
  shape: RoundedSuperellipseBorder(borderRadius: style.borderRadius.md),
  padding: .zero,
);

FTileContentStyle _tileContentStyle({
  required FColors colors,
  required FTypography typography,
  required Color prefix,
  required Color foreground,
  required Color mutedForeground,
}) {
  final disabledMutedForeground = colors.disable(mutedForeground);
  return FTileContentStyle(
    prefixIconStyle: FVariants.from(
      IconThemeData(color: prefix, size: typography.body.md.fontSize),
      variants: {
        [.disabled]: .delta(color: colors.disable(prefix)),
      },
    ),
    titleTextStyle: FVariants.from(
      typography.bodyPrimary.copyWith(color: foreground),
      variants: {
        [.disabled]: .delta(color: colors.disable(foreground)),
      },
    ),
    subtitleTextStyle: FVariants.from(
      typography.body.xs2.copyWith(color: mutedForeground),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    detailsTextStyle: FVariants.from(
      typography.bodyPrimary.copyWith(color: mutedForeground),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    suffixIconStyle: FVariants.from(
      IconThemeData(color: mutedForeground, size: typography.body.md.fontSize),
      variants: {
        [.disabled]: .delta(color: disabledMutedForeground),
      },
    ),
    suffixedPadding: const .fromSTEB(15, 14.5, 13, 14.5),
    unsuffixedPadding: const .symmetric(horizontal: 15, vertical: 14.5),
    prefixIconSpacing: 10,
    titleSpacing: 3,
    middleSpacing: 4,
    suffixIconSpacing: 5,
  );
}

FRawTileContentStyle _rawTileContentStyle({
  required FColors colors,
  required FTypography typography,
  required Color prefix,
  required Color color,
}) => FRawTileContentStyle(
  prefixIconStyle: FVariants.from(
    IconThemeData(color: prefix, size: typography.body.md.fontSize),
    variants: {
      [.disabled]: .delta(color: colors.disable(prefix)),
    },
  ),
  childTextStyle: FVariants.from(
    typography.bodyPrimary.copyWith(color: color),
    variants: {
      [.disabled]: .delta(color: colors.disable(color)),
    },
  ),
  padding: const .symmetric(horizontal: 15, vertical: 14.5),
  prefixIconSpacing: 10,
);
